variables:
  HTTP_PROXY: http://proxy3.lmco.com:80
  HTTPS_PROXY: http://proxy3.lmco.com:80
  http_proxy: http://proxy3.lmco.com:80
  https_proxy: http://proxy3.lmco.com:80
  NO_PROXY: 127.0.0.1,localhost
  GIT_SSL_NO_VERIFY: "true"
  GIT_STRATEGY: clone
  DTR_URL: dtr.mbx.us.lmco.com
  DTR_ORG: mbee
  DTR_REPO: dis
  DTR_TAG: latest
  DOCKER_URL: jfrog.swf.mbx.us.lmco.com
  DOCKER_ORG: mbx-docker
  DOCKER_REPO: dis
  DOCKER_TAG: latest

stages:
  - Docker

Docker Build & Push:
  stage: Docker
  tags:
    - docker-builder
  only:
    - develop
    - master
  script:
    - export DOCKER_URI=$DOCKER_URL/$DOCKER_ORG/$DOCKER_REPO
    - echo $ARTIFACTORY_API_KEY | docker login -u $ARTIFACTORY_USER $DOCKER_URL --password-stdin
    - docker build -t dis .
    - docker tag dis $DOCKER_URI
    - docker push $DOCKER_URI:$DOCKER_TAG
    - docker tag dis registry.gitlab.us.lmco.com:443/mbx/mbee/dynamic-integration-service/dis
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN registry.gitlab.us.lmco.com:443
    - docker push registry.gitlab.us.lmco.com:443/mbx/mbee/dynamic-integration-service/dis:latest
